### PR TITLE
Fix invalid warp message and add case-insensitive warp teleport

### PR DESCRIPTION
**Pull request by SenPr**
For #379 

Still very new to plugin development/contributing. The code isn't exactly top notch, sorry in advance
Also I made to intend for single server, so probably doesn't work for network setup.

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Thanks for your interest in helping out here!

The issue with this approach is that you're now having to query for every warp ever set on the server each time a user runs the command -- which is slow.

The SQL statement in the getWarp method is what probably needs changing to select all with a name irrespective of case

**Comment by SenPr** [comment]
That is probably what I should have looked at first...

Thanks, I'll try and see if I could do it, feel free to close the PR

**Comment by WiIIiam278** [comment]
No problem :) Please do feel free to have a go at doing that, everyone's gotta start somewhere with this stuff!

You'll want to look at the MySqlDatabase and SqLiteDatabase classes -- and probably do a bit of reading on how to update the SQL statement for getting a warp by name. Currently afaik it just does a WHERE name=? which is where the flaw with this is.

Maybe even have a look at the Unit Tests class in BukkitHuskHomes if you want a bit of a challenge and see about writing / editing the unit tests for querying warps so this can be caught more easily!

**Comment by SenPr** [comment]
Yeah I will leave that to you xD

For now, I made the SQL statements to use UPPER() and use .toUpperCase() for warpName. It works fine, but no idea on how that would work with cross-server/multi network stuff.

As for the message, its kind of a bandaid, I have no idea what the check in resolveWarp is doing, so I'm only adding ontop of it.

**Pull request closed without merging**
